config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :addresses
  resources :users do
    collection do
      post 'update-status' => 'users#update_status' 
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users 
    end
  end

  mount ActionCable.server => '/cable'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    acts_as_paranoid
    has_many :addresses, :dependent => :destroy
    accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true

    validates :name, presence: true

    enum status: { active: 'Active', inactive: 'Inactive' }
    enum gender: { male: 'Male', female: 'Female', other: 'Other' }

    def self.generate
        
    end

    def self.pick_one
        self.order(Arel.sql('RANDOM()')).first
    end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
	skip_before_action :verify_authenticity_token
	before_action :set_user, only: %i[ show update destroy update_status]

	def index
		@users = User.all
		render json: {success: 1, data: {users: @users}, error: {}}
	end

	def create
		@user = User.new(user_params)

		if @user.save
			render json: {success: 1, message: 'User created successfully!', data: {user: @user}}
		else
			render json: {success: 0, message: 'Error while creating user', data: {}, error: @user.errors}, status: 400
		end
	end

	def update
		if @user.update(user_params)
			render json: {success: 0, message: 'User updated successfully!', data: {user: @user}, error: {}}
		else
			render json: {success: 0, message: 'Error while updating user', error: @user.errors}, status: 400
		end
	end

	def destroy
		if @user.destroy
			render json: {success: 1, message: 'User deleted successfully!', data: {}, error: {}}
		else
			render json: {success: 0, message: 'Error while deleting user', data: {}, error: {}}, status: 400
		end
	end

	private
		def set_user
			@user = User.find(params[:id])
		end

		def user_params
			params.require(:user).permit(:name, :dob, :gender, :status)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy update_status ]
  before_action :current_user

  # GET /users or /users.json
  def index
    ActionCable.server.broadcast "activity_channel", user_id: current_user.id, status: 'online'
    file = File.read(Rails.root.join('storage/online_users.json'))
    data_hash = JSON.parse(file)
    @currently_online = data_hash['users']
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
    3.times { @user.addresses.build }
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_status
    params.permit :id, :active
    user_id = params[:id]
    status = (params[:active] == 'true') ? 'active' : 'inactive'
    
    user = User.find(user_id)
    user.status = status
    output = 
      if user.save
        {success: 1, message: 'Status Changed successfully!', status: user.status}.to_json
      else
        {success: 0, message: 'Error in status change', status: user.status}.to_json
      end

    render :json => output
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(
        :name, :dob, :gender, :status,
        addresses_attributes: [ :id, :address, :_destroy ]
      )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_address_fields.html.erb
<div class="row m-2">
    <div class="col-6">
        <%= f.text_area :address, :rows => 3, class: "form-control" %>
    </div>
    <div class="col-6">
        <%= f.check_box :_destroy, class: "form-check-input" %>
        <%= f.label :_destroy, "Delete this address", class: "form-check-label" %>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, class: "form ") do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>




  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Date of Birth" %>
    <%= form.date_field :dob, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.select :gender, 
          options_for_select( User.genders.map { |key, value| [key.titleize, User.genders.key(value)] }, user.gender ),
          {},
          {class: "form-control"}
    %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select :status, 
          options_for_select( User.statuses.map { |key, value| [key.titleize, User.statuses.key(value)] }, user.status ), 
          {},
          {class: "form-control"}  
    %>
  </div>

  <div class="form-group">
    <%= form.label "Addresses" %>
      <%= form.fields_for :addresses do |builder| %>
        <%= render 'address_fields', f: builder %>
      <% end %>

    <%= link_to_add_fields 'Add Address', form, :addresses %>
  </div>

  <%= form.submit(user.new_record? ? "Create user" : "Update user", class: "btn btn-primary") %>

<% end %>

<script>
$("[data-form-prepend]").click(function(e) {
  e.preventDefault();
  var obj = $($(this).attr("data-form-prepend"));
  obj.find("input, select, textarea").each(function() {
    $(this).attr("name", function() {
      return $(this)
        .attr("name")
        .replace("new_record", new Date().getTime());
    });
  });
  obj.insertBefore(this);
  return false;
});
</script>

app/views/users/edit.html.erb
<div class="container">
    <h1>Editing User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Show', @user, class: "btn btn-link" %> |
    <%= link_to 'Back', users_path, class: "btn btn-link" %>

</div>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <h1>Users</h1>
  <h5>Currently logged in as <b><%= current_user.name %></b></h5>
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th>Name</th>
        <th>Dob</th>
        <th>Gender</th>
        <th>Status</th>
        <th># of Addresses</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><span class="online-status user-<%= user.id %>-status <%= 'online' if ((current_user.id == user.id) || (@currently_online.include? user.id)) %>">●</span><%= user.name %></td>
          <td><%= user.dob %></td>
          <td><%= user.gender %></td>
          <td>
            <div class="custom-control custom-switch">
              <input type="checkbox" class="custom-control-input status-updater" <%= "checked" if user.status == 'active'%> id="customSwitch_<%= user.id %>" data-id="<%= user.id %>">
              <label class="custom-control-label" for="customSwitch_<%= user.id %>" id="check-label-<%= user.id %>"><%= user.status.titleize %></label>
            </div>
          </td>
          <td><%= user.addresses.count %></td>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New User', new_user_path %>
</div>

<script>
$(document).on('change', '.status-updater', function(e){
  let selId = $(this).data('id')

  $.post( "<%= update_status_users_path %>",
    {
      id: selId,
      active: $(this).is(':checked')
    },
    function( data ) {
      alert(data.message);
    }
  );

  if ($(this).is(':checked')) {
    $("#check-label-"+selId).text('Active')
  } else {
    $("#check-label-"+selId).text('Inactive')
  }
})
</script>

app/views/users/new.html.erb
<div class="container">
    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container"> 
 <p id="notice"><%= notice %></p>

  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>Dob:</strong>
    <%= @user.dob %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= @user.gender %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @user.status %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-outline-primary" %> 
  <%= link_to 'Back', users_path, class: "btn btn-outline-info" %>

  <h3>Addresses</h3>
  <table class="table table-striped">
    <thead class="thead-light">
      <tr>
        <th>ID</th>
        <th>Address</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @user.addresses.each do |address| %>
      <tr>
        <td><%= address.id %></td>
        <td><%= address.address %></td>
        <td>
          <%= link_to "View", address_path(address) %> | 
          <%= link_to "Delete", address_path(address), method: :delete  %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div>